# Generated by Django 3.2 on 2023-05-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='province_eqnum',
            table='province_eqnum_year',
        ),
    ]
