# Generated by Django 3.2 on 2023-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0006_province_intro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provine_magnitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('minn', models.FloatField()),
                ('averge', models.FloatField()),
                ('maxx', models.FloatField()),
            ],
            options={
                'db_table': 'province_magnitude',
            },
        ),
    ]
