# Generated by Django 3.2 on 2023-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0007_provine_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='provine_magnitude',
            name='f',
            field=models.FloatField(default=0),
        ),
    ]
