# Generated by Django 3.2 on 2023-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0008_provine_magnitude_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepth', models.FloatField()),
                ('grade', models.FloatField()),
                ('cluster', models.IntegerField()),
            ],
        ),
    ]
