# Generated by Django 3.2 on 2023-06-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0009_cluserdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cluserdata',
            table='clusterData',
        ),
    ]
