# Generated by Django 3.2 on 2023-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0010_alter_cluserdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchAreaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('magnitude', models.FloatField()),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'searchAreaData',
            },
        ),
    ]
