# Generated by Django 3.2 on 2023-07-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0011_searchareadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('magnitude', models.FloatField()),
            ],
            options={
                'db_table': 'predictionData',
            },
        ),
    ]
