# Generated by Django 3.2 on 2023-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0012_predictiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='doubleBarMagnitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('sMagnitude', models.FloatField()),
                ('mMagnitude', models.FloatField()),
                ('lMagnitude', models.FloatField()),
                ('sDepth', models.FloatField()),
                ('mDepth', models.FloatField()),
                ('lDepth', models.FloatField()),
            ],
        ),
    ]
