# Generated by Django 3.2 on 2023-07-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0013_doublebarmagnitude'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doublebarmagnitude',
            table='doubleBarData',
        ),
    ]
