# Generated by Django 3.2 on 2023-07-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0014_alter_doublebarmagnitude_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='pieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('depth', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('magnitudeTag', models.CharField(max_length=10)),
                ('depthTag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pieData',
            },
        ),
    ]
